### ISSUE TITLE
Unable to login Caldera - http://[10.0.1.12:8888/] - Local Build

### ISSUE THREAD

**Issue by secbaymax** [splunk/attack_range#414]
@P4T12ICK - Built single Splunk Server/Caldera local

**************************************************************************
Unable to login to caldera.

Tried logging in as both red and admin.
Password changed in config file and tried default as well.

************* Login screen returns back to login

**Comment by P4T12ICK** [comment]
Okay. I will fix that.

**Comment by P4T12ICK** [comment]
should be fixed. Please let me know if it's working for you.

**Comment by secbaymax** [comment]
![image](https://user-images.githubusercontent.com/57216696/99992326-3464ac00-2ddc-11eb-9cfe-fd725a678da7.png)

it's still not working ... i tried admin, red and blue 
and verified password in local conf file and as well tried without changing conf with default 
'
![image](https://user-images.githubusercontent.com/57216696/99993050-282d1e80-2ddd-11eb-96f3-328ea153ca9c.png)

**Comment by secbaymax** [comment]
@P4T12ICK - attached above log for further analysis

**Comment by P4T12ICK** [comment]
You got the latest version of the https://github.com/splunk/attack_range_local project? For me it was working.

**Comment by P4T12ICK** [comment]
the password is stored under the key caldera_password in attack_range_local.conf

**Comment by secbaymax** [comment]
It's working.. Now, after removing completely and rebuild. Thanks a lot @P4T12ICK !!!

However, in order to enable "mock" plugin in caldera. I need to restart caldera alone. Is there a way I can restart caldera, without losing my work on caldera?

**Comment by secbaymax** [comment]
> It's working.. Now, after removing completely and rebuild. Thanks a lot @P4T12ICK !!!
> 
> However, in order to enable "mock" plugin in caldera. I need to restart caldera alone. Is there a way I can restart caldera, without losing my work on caldera?

Is it possible to run safe restart of server.py of caldera ???

**Comment by P4T12ICK** [comment]
@secbaymax you're welcome. I don't know. For this question you nee to ask the guys from Caldera.
